apiVersion: v1
kind: Service
metadata:
  name: wordpress-site-id
  labels:
    app.kubernetes.io/app: wordpress
    app.kubernetes.io/instance: wordpress-site-id
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: wordpress-operator
spec:
  ports:
    - port: 80
      name: http
  clusterIP: None
  selector:
    app: wordpress-site-id