apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-site-id
  labels:
    app.kubernetes.io/app: wordpress-site-id
    app.kubernetes.io/instance: wordpress-site-id
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: wordpress-operator
spec:
  selector:
    matchLabels:
      app: wordpress-site-id
  serviceName: wordpress-site-id
  template:
    metadata:
      labels:
        app: wordpress-site-id
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - sites
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "sites"
        effect: "NoSchedule"
      initContainers:
        - name: wordpress-copy-files
          image: wordpress:php8.3-apache
          command:
                - /bin/sh
                - -c
                - |
                  # Copier les fichiers WordPress si le volume est vide
                  if [ ! -f /var/www/html/index.php ]; then
                    echo "📦 Copie des fichiers WordPress..."
                    cp -r /usr/src/wordpress/* /var/www/html
                  fi
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
        - name: wp-init
          image: wordpress:cli
          env:
            - name: WORDPRESS_DB_HOST
              value: db_host
            - name: WORDPRESS_DB_NAME
              value: db_name
            - name: WORDPRESS_DB_USER
              value: db_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret-name
                  key: db_password_secret_key
            - name: HTTP_HOST
              value: wordpress-base-url
            - name: WP_ADMIN_USER
              value: admin
            - name: WP_ADMIN_PASSWORD
              value: password
            - name: WP_ADMIN_EMAIL
              value: admin@example.com
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: wordpress-config
              mountPath: /var/www/html/wp-config.php
              subPath: wp-config.php
          command:
            - /bin/sh
            - -c
            - |
              # Installer WordPress si pas déjà installé
              wp core is-installed --path=/var/www/html
              rc=$?

              if [ "$rc" -eq 0 ]; then
                echo "✅ WordPress déjà installé"
              else
                echo "🚀 Installation WordPress..."
                wp core install \
                  --url="$HTTP_HOST" \
                  --title="Mon site WordPress" \
                  --admin_user="$WP_ADMIN_USER" \
                  --admin_password="$WP_ADMIN_PASSWORD" \
                  --admin_email="$WP_ADMIN_EMAIL" \
                  --path=/var/www/html
              fi
      containers:
        - name: wordpress
          image: wordpress:php8.3-apache
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORDPRESS_DB_HOST
              value: db_host
            - name: WORDPRESS_DB_NAME
              value: db_name
            - name: WORDPRESS_DB_USER
              value: db_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret-name
                  key: db_password_secret_key
            - name: HTTP_HOST
              value: wordpress-base-url
            - name: WP_SITE_PATH
              value: /wp-site-path
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: wordpress-config
              mountPath: /var/www/html/wp-config.php
              subPath: wp-config.php
            - mountPath: /etc/apache2/sites-enabled/000-default.conf
              name: apache-config
              subPath: httpd.conf
          resources:
            requests:
              memory: "30Mi"
              cpu: "5m"
            limits:
              memory: "50Mi"
              cpu: "50m"
      volumes:
        - name: wordpress-data
          emptyDir: {}
        - name: wordpress-config
          configMap:
            name: wordpress-site-id-wordpress-configmap
        - name: apache-config
          configMap:
            name: wordpress-site-id-apache-configmap